src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity("username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToMany(targetEntity=Planning::class, mappedBy="members")
     */
    private $plannings;

    public function __construct()
    {
        $this->plannings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Planning[]
     */
    public function getPlannings(): Collection
    {
        return $this->plannings;
    }

    public function addPlanning(Planning $planning): self
    {
        if (!$this->plannings->contains($planning)) {
            $this->plannings[] = $planning;
            $planning->addMember($this);
        }

        return $this;
    }

    public function removePlanning(Planning $planning): self
    {
        if ($this->plannings->removeElement($planning)) {
            $planning->removeMember($this);
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username', TextType::class)
            ->add('roles', ChoiceType::class, [
                'multiple' => false,
                'expanded' => true,
                'choices' => [
                    'Admin' => 'ROLE_ADMIN',
                    'Manager' => 'ROLE_MANAGER',
                    'User' => 'ROLE_USER'
                ],
            ])
            ->add('submit', SubmitType::class)
        ;

        $builder->get('roles')->addModelTransformer(new CallbackTransformer(
            function ($array) {
                if (in_array('ROLE_ADMIN', $array)) return 'ROLE_ADMIN';
                if (in_array('ROLE_MANAGER', $array)) return 'ROLE_MANAGER';
                return 'ROLE_USER';
            },
            function ($string) {
                return [$string];
            }
        ));
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\NewUserType;
use App\Form\UserPasswordType;
use App\Form\UserType;
use App\Service\UserFormService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_list")
     */
    public function index(): Response
    {
        $users = $this->getDoctrine()->getRepository(User::class)->findAll();

        return $this->render('user/index.html.twig', [
            'users' => $users
        ]);
    }

    /**
     * @Route("/create", name="user_create")
     * @IsGranted("ROLE_MANAGER")
     */
    public function create(Request $request, UserFormService $formService): Response
    {
        $user = new User();
        $form = $this->createForm(NewUserType::class, $user);

        $form->handleRequest($request);

        $isCreated = $formService->create($form);

        if ($isCreated) {
            $this->addFlash('success', 'User ' . $user->getUserIdentifier() . ' created');

            return $this->redirectToRoute('user_list');
        }

        return $this->renderForm('user/create.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="user_delete")
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(User $user): Response
    {
        if ($user->getId() === $this->getUser()->getId()) {
            $this->addFlash('warning', 'You shouldn\'t try to delete yourself...');

            return $this->redirectToRoute('user_list');
        }

        $om = $this->getDoctrine()->getManager();
        $om->remove($user);
        $om->flush();

        $this->addFlash('success', 'User ' . $user->getUserIdentifier() . ' is deleted');

        return $this->redirectToRoute('user_list');
    }

    /**
     * @Route("/edit/{id}", name="user_edit")
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'User ' . $user->getUserIdentifier() . ' is updated');

            return $this->redirectToRoute('user_list');
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form
        ]);
    }

    /**
     * @Route("/change_password/{id}", name="user_change_password")
     * @IsGranted("ROLE_ADMIN")
     */
    public function changePassword(
        Request $request,
        User $user,
        UserFormService $formService
    ): Response
    {
        $form = $this->createForm(UserPasswordType::class);
        $form->handleRequest($request);

        $isUpdated = $formService->updatePassword($user, $form);

        if ($isUpdated) {
            $this->addFlash('success', 'Password for ' . $user->getUserIdentifier() . ' user is updated');

            return $this->redirectToRoute('user_list');
        }

        return $this->renderForm('user/change_password.html.twig', [
            'form' => $form
        ]);
    }
}

templates/user/change_password.html.twig
{% extends 'app/layouts/card.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block card_header %}
    Change user password
{% endblock %}

{% block card_body %}
    {{ form_start(form) }}
    {{ form_row(form.password) }}
    {{ form_row(form.passwordConfirm) }}
    <button type="submit">Update</button>
    {{ form_end(form)}}
{% endblock %}

templates/user/create.html.twig
{% extends 'app/layouts/card.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block card_header %}
    Create new user
{% endblock %}

{% block card_body %}
    {{ form_start(form) }}
    {{ form_row(form.username) }}
    {{ form_row(form.roles) }}
    {{ form_widget(form.password) }}
    {{ form_row(form.submit) }}
    {{ form_end(form)}}
{% endblock %}

templates/user/edit.html.twig
{% extends 'app/layouts/card.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block card_header %}
    Edit {{ user.userIdentifier }} user
{% endblock %}

{% block card_body %}
    {{ form_start(form) }}
    {{ form_row(form.username) }}
    {{ form_row(form.roles) }}
    {{ form_row(form.submit) }}
    {{ form_end(form)}}
{% endblock %}

templates/user/index.html.twig
{% extends 'app/layouts/datatable.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block card_header %}
    <h3>User list</h3>
    <a href="{{ path('user_create') }}" class="btn btn-sm btn-success">Create</a>
{% endblock %}

{% block card_body %}
    <table id="" class="table table-bordered table-hover datatable-init">
        <thead>
        <tr>
            <th style="width: auto;">Id</th>
            <th>Username</th>
            <th>Roles</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.userIdentifier }}</td>
            <td>{{ user.roles|join(', ') }}</td>
            <td>
                <div class="btn-group">
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('user_delete', {id: user.id}) }}" class="btn btn-xs btn-danger" data-toggle="confirmation" data-title="Are you sure you want to delete this user?">&nbsp;X&nbsp;</a>
                    {% endif %}
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('user_edit', {id: user.id}) }}" class="btn btn-xs btn-warning">&nbsp;E&nbsp;</a>
                    {% endif %}
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('user_change_password', {id: user.id}) }}" class="btn btn-xs btn-warning">&nbsp;P&nbsp;</a>
                    {% endif %}
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}